version: '3.3'

services:
  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: development

  mongo-express:
    image: mongo-express:latest  # Added the image field for mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGO_INITDB_ROOT_USERNAME: development  # Fixed the environment variable key
      ME_MONGO_INITDB_ROOT_USERNAME: development
      ME_CONFIG_MONGODB_URL: mongodb://development:development@mongo:27017/
